export const MessageTypes = {
    ping: 'PING',
    pong: 'PONG',
    response: 'RESPONSE',
    authentication: 'AUTH',
    follow: 'CHANNEL.FOLLOW',
    ban: 'CHANNEL.BAN',
    unban: 'CHANNEL.UNBAN',
    channelPointsAddReward: 'CHANNEL.REWARD.ADD',
    channelPointsUpdateReward: 'CHANNEL.REWARD.UPDATE',
    channelPointsRemoveReward: 'CHANNEL.REWARD.REMOVE',
    channelPointsRedeemReward: 'CHANNEL.REWARD.REDEMPTION.ADD',
    channelPointsUpdateRedemption: 'CHANNEL.REWARD.REDEMPTION.UPDATE',
    channelUpdate: 'CHANNEL.UPDATE',
    channelCheer: 'CHANNEL.CHEER',
    channelGoalBegin: 'CHANNEL.GOAL.BEGIN',
    channelGoalProgress: 'CHANNEL.GOAL.PROGRESS',
    channelGoalEnd: 'CHANNEL.GOAL.END',
    channelHypeTrainBegin: 'CHANNEL.HYPE_TRAIN.BEGIN',
    channelHypeTrainProgress: 'CHANNEL.HYPE_TRAIN.PROGRESS',
    channelHypeTrainEnd: 'CHANNEL.HYPE_TRAIN.END',
}